name: sign_in
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter
  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields
  domain_models:
    path: ../../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  mockito: ^5.2.0
  test: ^1.16.8
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
